// Generated by Selenium IDE

import io.github.bonigarcia.wdm.WebDriverManager;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.Select;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;
import pages.RegistrationFormPage;
import utils.Utils;

import java.util.*;
public class RegistrationTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeClass
  public void setUp() {
    WebDriverManager.chromedriver().setup();
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @AfterClass
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void registration() throws InterruptedException {
    driver.get("http://automationpractice.com/index.php");
    driver.manage().window().setSize(new Dimension(1382, 744));
    Thread.sleep(3000);
    driver.findElement(By.linkText("Sign in")).click();


    //assertThat(driver.findElement(By.cssSelector("#create-account_form > .page-subheading")).getText(), is("CREATE AN ACCOUNT"));
    //assertThat(driver.findElement(By.cssSelector(".form_content > p:nth-child(1)")).getText(), is("Please enter your email address to create an account."));
    {
      WebElement element = driver.findElement(By.cssSelector(".page-heading"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    Thread.sleep(3000);
    driver.findElement(By.id("email_create")).sendKeys("oncharrvhgrui0071@onch.com");


    driver.findElement(By.cssSelector("#SubmitCreate > span")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".page-heading")));
    }
    Thread.sleep(3000);
    //driver.findElement(By.id("id_gender1")).click();

    By customerFirstname = By.id("customer_firstname");
    WebElement element = Utils.waitForElementPresence(driver,customerFirstname,30);

    element.sendKeys("Arrhgfehhlu");
    driver.findElement(By.id("customer_lastname")).sendKeys("Makori");

    driver.findElement(By.id("passwd")).sendKeys("1234567890");

   Select date = new Select(driver.findElement(By.id("days")));
    Select month = new Select(driver.findElement(By.id("months")));
   Select year = new Select(driver.findElement(By.id("years")));
    date.selectByValue("1");
    month.selectByValue("12");
    year.selectByValue("2005");




    driver.findElement(By.cssSelector("#years > option:nth-child(17)")).click();
    driver.findElement(By.id("newsletter")).click();
    driver.findElement(By.id("optin")).click();
    driver.findElement(By.id("company")).click();
    driver.findElement(By.id("company")).sendKeys("Geonax");
    driver.findElement(By.id("address1")).click();
    driver.findElement(By.id("address1")).sendKeys("7776 Kisii");
    driver.findElement(By.id("address2")).click();
    driver.findElement(By.id("address2")).sendKeys("Uoni Kenya");
    driver.findElement(By.id("city")).click();
    driver.findElement(By.id("city")).sendKeys("Kisumu");
    driver.findElement(By.id("id_state")).click();
    {
      WebElement dropdown = driver.findElement(By.id("id_state"));
      dropdown.findElement(By.xpath("//option[. = 'Illinois']")).click();
    }
    driver.findElement(By.cssSelector("#id_state > option:nth-child(15)")).click();
    driver.findElement(By.id("postcode")).click();
    driver.findElement(By.id("postcode")).sendKeys("34543");
    driver.findElement(By.id("id_country")).click();
    driver.findElement(By.cssSelector("#id_country > option:nth-child(2)")).click();
    driver.findElement(By.id("other")).click();
    driver.findElement(By.id("other")).sendKeys("I will be okay");
    driver.findElement(By.id("phone")).click();
    driver.findElement(By.id("phone")).sendKeys("0712334443");
    driver.findElement(By.id("phone_mobile")).click();
    driver.findElement(By.id("phone_mobile")).sendKeys("0710664345");
    driver.findElement(By.id("alias")).click();
    driver.findElement(By.id("alias")).click();
    driver.findElement(By.id("alias")).sendKeys("Kemoni");
    driver.findElement(By.cssSelector("#submitAccount > span")).click();
   // assertThat(driver.findElement(By.cssSelector(".page-heading")).getText(), is("MY ACCOUNT"));
    //assertThat(driver.findElement(By.cssSelector(".info-account")).getText(), is("Welcome to your account. Here you can manage all of your personal information and orders."));
    //assertThat(driver.findElement(By.linkText("Sign out")).getText(), is("Sign out"));
    //assertThat(driver.findElement(By.cssSelector(".account > span")).getText(), is("Dennis Makori"));
    driver.findElement(By.linkText("Sign out")).click();
    driver.findElement(By.cssSelector(".logo")).click();
  }
}
