// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class Signup2Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void signup2() {
    driver.get("http://automationpractice.com/index.php");
    driver.manage().window().setSize(new Dimension(1550, 848));
    driver.findElement(By.linkText("Sign in")).click();
    driver.findElement(By.id("email_create")).click();
    driver.findElement(By.id("email_create")).sendKeys("onchari202@gmail.com");
    driver.findElement(By.cssSelector("#SubmitCreate > span")).click();
    driver.findElement(By.id("id_gender1")).click();
    driver.findElement(By.id("customer_firstname")).click();
    driver.findElement(By.id("customer_firstname")).sendKeys("Agnes");
    driver.findElement(By.id("customer_lastname")).click();
    driver.findElement(By.id("customer_lastname")).sendKeys("Mokueia");
    driver.findElement(By.id("passwd")).click();
    driver.findElement(By.id("passwd")).sendKeys("123456@Aut");
    driver.findElement(By.cssSelector(".account_creation:nth-child(1) > .required:nth-child(5)")).click();
    driver.findElement(By.id("days")).click();
    {
      WebElement dropdown = driver.findElement(By.id("days"));
      dropdown.findElement(By.xpath("//option[. = 'regexp:19\s+']")).click();
    }
    driver.findElement(By.cssSelector("#days > option:nth-child(20)")).click();
    driver.findElement(By.id("months")).click();
    {
      WebElement dropdown = driver.findElement(By.id("months"));
      dropdown.findElement(By.xpath("//option[. = 'regexp:December\s']")).click();
    }
    driver.findElement(By.cssSelector("#months > option:nth-child(13)")).click();
    driver.findElement(By.id("years")).click();
    {
      WebElement dropdown = driver.findElement(By.id("years"));
      dropdown.findElement(By.xpath("//option[. = 'regexp:1977\s+']")).click();
    }
    driver.findElement(By.cssSelector("#years > option:nth-child(44)")).click();
    driver.findElement(By.id("newsletter")).click();
    driver.findElement(By.id("optin")).click();
    driver.findElement(By.id("firstname")).click();
    driver.findElement(By.id("company")).click();
    driver.findElement(By.id("company")).sendKeys("Cellulant ");
    driver.findElement(By.id("address1")).click();
    driver.findElement(By.id("address1")).sendKeys("Cellulant West End Towers");
    driver.findElement(By.id("address2")).click();
    driver.findElement(By.id("address1")).click();
    driver.findElement(By.id("address2")).click();
    driver.findElement(By.id("address2")).sendKeys(Keys.DOWN);
    driver.findElement(By.id("address2")).sendKeys("Nagi Palza, 2nd floor suit 5");
    driver.findElement(By.id("city")).click();
    driver.findElement(By.id("city")).sendKeys(Keys.DOWN);
    driver.findElement(By.id("city")).sendKeys("Nairobi");
    driver.findElement(By.id("id_state")).click();
    {
      WebElement dropdown = driver.findElement(By.id("id_state"));
      dropdown.findElement(By.xpath("//option[. = 'Kentucky']")).click();
    }
    driver.findElement(By.cssSelector("#id_state > option:nth-child(19)")).click();
    driver.findElement(By.id("postcode")).click();
    driver.findElement(By.id("postcode")).sendKeys("34556");
    driver.findElement(By.id("id_country")).click();
    driver.findElement(By.cssSelector("#id_country > option:nth-child(2)")).click();
    driver.findElement(By.id("other")).click();
    driver.findElement(By.id("other")).sendKeys("If you find me offline in the work line please call me on home phone");
    driver.findElement(By.id("phone")).click();
    driver.findElement(By.id("phone")).click();
    {
      WebElement element = driver.findElement(By.id("phone"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("phone")).sendKeys("07656575676");
    driver.findElement(By.id("phone_mobile")).click();
    driver.findElement(By.id("phone_mobile")).click();
    {
      WebElement element = driver.findElement(By.id("phone_mobile"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("phone_mobile")).sendKeys("071045333344");
    driver.findElement(By.id("alias")).click();
    driver.findElement(By.id("alias")).click();
    driver.findElement(By.id("alias")).sendKeys("Nagi home");
    driver.findElement(By.cssSelector("#submitAccount > span")).click();
    driver.findElement(By.cssSelector(".page-heading")).click();
    assertThat(driver.findElement(By.cssSelector(".page-heading")).getText(), is("MY ACCOUNT"));
    assertThat(driver.findElement(By.cssSelector(".account > span")).getText(), is("Agnes Mokueia"));
    driver.findElement(By.cssSelector(".info-account")).click();
    assertThat(driver.findElement(By.cssSelector(".info-account")).getText(), is("Welcome to your account. Here you can manage all of your personal information and orders."));
    driver.findElement(By.linkText("Sign out")).click();
  }
}
